month-8/step-1
w0lrid/react-burger pull request #3
Opened 2023-04-23 18:18 UTC by w0lrid

2023-04-23 18:41 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Контекст настроен и используется верно
- Нет лишнего кода
- Есть подсчёт стоимости заказа

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку ответа сервера - res.ok:
- Запрос на номер заказа падает - у вас не хватает в опциях запроса поля в хедерах свойства Content-Type.
https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Type
- Необходимо показывать не моковый номер заказа, а тот, что получаете с помощью запроса.  
- Модалка должна портироваться в DOM через `createPortal`. 
- рендерите компонент попапа только если он нужен на странице

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-23 18:41 UTC, andryxxa93 commented on src/components/app/app.jsx
> +          <IngredientsContext.Provider value={{ingredients, setIngredients}}>
**Можно лучше**

такая запись значения контекста приводит к тому, что при каждом рендере App даже не связанным с изменением значения контекста будет создаватсья новый объект и передаваться новое значение контекста, это приведет к перерендеру всех компонентов использующих контекст

Нужно обернуть создание объекта в useMemo, как показано в этой статье https://hswolff.com/blog/how-to-usecontext-with-usereducer/ в разделе Performance Concerns

2023-04-23 18:41 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }).then((response) => {
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-04-23 18:41 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const buns = ingredients.filter(({type}) => type === 'bun')
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-04-23 18:41 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +      method: 'POST',
**Необходимо исправить**
- Запрос на номер заказа падает - у вас не хватает в опциях запроса поля в хедерах свойства Content-Type.

2023-04-23 18:41 UTC, andryxxa93 commented on src/components/app/app.jsx
> +                  <BurgerIngredients data={ingredients} handleIngredientInfo={handleIngredientInfo}/>
**Можно лучше**
Функции можно так же передавать через контекст

2023-04-23 18:41 UTC, andryxxa93 commented on src/components/app/app.jsx
> +            </Modal>
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```
{isOpen && (
    компонент открываемого попапа
)}
``

2023-04-24 09:13 UTC, w0lrid commented on src/components/app/app.jsx
> +            </Modal>
@andryxxa93 Переписал, потерялась плавность открытия попапа из-за условного рендеринга. Условный рендеринг и плавное открытие попапа реально совместить без лютых костылей?

2023-04-24 18:58 UTC, andryxxa93 commented on src/components/app/app.jsx
> +            </Modal>
Да, тут есть такой ньанс. Но для плавность можно или стилями решить, т.е. сначала портировать модалку, а только потом показыват её плавно, но вот с сокрытием так уже не получится - для этой цели есть библиотеки - `https://blog.logrocket.com/best-react-animation-library-top-7-libraries-compared/`

2023-04-24 19:00 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-24 19:00 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const ingredientModal = createPortal((
**Можно лучше**
`createPortal ` нужно использовать только один раз внутри компонента Модалки.

2023-04-30 07:34 UTC, merged