Month 9/step 1
w0lrid/react-burger pull request #5
Opened 2023-09-18 19:09 UTC by w0lrid

2023-09-18 19:27 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Использовали тег форм
- Есть защита роутов
- Использовали куки для хранения токенов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Проект собирается с ошибками

<img width="1440" alt="Снимок экрана 2023-09-18 в 22 18 43" src="https://github.com/w0lrid/react-burger/assets/60173362/bfcca689-f624-4fc7-b416-903a87a214b3">

<img width="1440" alt="Снимок экрана 2023-09-18 в 22 23 28" src="https://github.com/w0lrid/react-burger/assets/60173362/9c8ea3df-a300-43de-aab1-9bf8232104c6">

- на тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.

- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

Для этого используйте обертку над fetch, примерно такую

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Пожалуйста, посоветуйтесь с наставником.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-18 19:27 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        <Route path="/login" element={<LoginPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-09-18 19:27 UTC, andryxxa93 commented on src/pages/forgotAndResetPassword.jsx
> +  if (accessToken.length > 0) {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-09-18 19:27 UTC, andryxxa93 commented on src/pages/forgotAndResetPassword.jsx
> +    fetch('https://norma.nomoreparties.space/api/password-reset', {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-09-19 16:52 UTC, w0lrid commented on src/components/app/app.jsx
> +        <Route path="/login" element={<LoginPage />} />
Не уловил, к чему это относится

2023-09-19 18:35 UTC, andryxxa93 commented
**Необходимо исправить**

- При прямом переходе страницу ингредиента - пустая страница

<img width="920" alt="Снимок экрана 2023-09-19 в 21 34 46" src="https://github.com/w0lrid/react-burger/assets/60173362/885e3f77-3517-4cbe-892e-9198dc91e8da">

2023-09-20 13:30 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-25 15:49 UTC, merged